# Copyright 2023 Google LLC
# Copyright 2026 StepSecurity
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Non-Bazel Bash Run'
description: 'Run a bash script for Protobuf CI testing with a non-Bazel build system'
inputs:
  credentials:
    required: true
    description: "The GCP credentials to use for reading the docker image"
    type: string
  command:
    required: true
    description: A command to run in the docker image
  bazel-version:
    required: false
    description: Bazel version to use
    default: "8.0.1"
    type: string
  bazel-flags:
    required: false
    description: Bazel flags to use for staleness regen
    type: string

runs:
  using: 'composite'
  steps:
    - name: Subscription check
      run: |
        # validate subscription status
        API_URL="https://agent.api.stepsecurity.io/v1/github/$GITHUB_REPOSITORY/actions/subscription"

        # Set a timeout for the curl command (3 seconds)
        RESPONSE=$(curl --max-time 3 -s -w "%{http_code}" "$API_URL" -o /dev/null) || true
        CURL_EXIT_CODE=$?

        # Decide based on curl exit code and HTTP status
        if [ $CURL_EXIT_CODE -ne 0 ]; then
          echo "Timeout or API not reachable. Continuing to next step."
        elif [ "$RESPONSE" = "200" ]; then
          :
        elif [ "$RESPONSE" = "403" ]; then
          echo "Subscription is not valid. Reach out to support@stepsecurity.io"
          exit 1
        else
          echo "Timeout or API not reachable. Continuing to next step."
        fi
      shell: bash

    - name: Symlink current Actions repo
      env:
        GH_ACTION_DIR: ${{ github.workspace }}/../../_actions/${{ github.action_repository }}/${{ github.action_ref }}/
        GH_ACTION_CLONE: ${{ github.workspace }}/../../_actions/current
      shell: bash
      run: ln -fs $GH_ACTION_DIR $GH_ACTION_CLONE

    - name: Setup Runner
      uses: ./../../_actions/current/internal/setup-runner

    - name: Update stale files using Bazel
      uses: ./../../_actions/current/bazel
      with:
        credentials: ${{ inputs.credentials }}
        bazel-cache: regenerate-stale-files
        bash: ./regenerate_stale_files.sh $BAZEL_FLAGS
        bazel-flags: ${{ inputs.bazel-flags }}
        version: ${{ inputs.bazel-version }}

    - name: Run
      shell: bash
      run: ${{ inputs.command }}
